# Generated by Django 4.2 on 2023-04-19 11:26

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_alter_meeting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(blank=True,  max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='desciption',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Host+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='purpose',
            field=models.CharField(choices=[('PERSONAL', 'personal'), ('GROUPY', 'groupy'), ('ORGANIZATIONAL', 'organizational'), ('OLM', 'online meeting(friendly)')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='MeetingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='meetingresources/'), upload_to='meetingresources/')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='meetings.meeting')),
            ],
        ),
    ]
