# Generated by Django 4.2 on 2023-04-19 11:37

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0004_remove_meeting_user_meeting_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(blank=True,  max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='desciption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Host+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meetingresource',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='meetingresources/'), upload_to='meetingresources/'),
        ),
    ]
