# Generated by Django 4.2 on 2023-04-22 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_groupattendee_groupmessage_delete_groutactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupattendee',
            name='user',
        ),
        migrations.AddField(
            model_name='groupattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee+', to=settings.AUTH_USER_MODEL),
        ),
    ]
