# Generated by Django 4.2 on 2023-04-19 11:26

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0003_alter_tutorial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='user',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True,  null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='lesson',
            field=models.CharField(blank=True,  max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tuitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TutorialResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='tutorialresources/'), upload_to='tutorialresources/')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial')),
            ],
        ),
    ]
