# Generated by Django 4.2 on 2023-04-19 11:37

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0004_remove_tutorial_user_tutorial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True,  null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='lesson',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tuitor',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='tutorialresources/'), upload_to='tutorialresources/'),
        ),
    ]
